meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: covalence
    templates:
    - name: covalence_agent
      release: covalence
    - name: covalence_api
      release: covalence
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set covalence networks" ))

networks: (( param "please set networks" ))

properties:
  covalence_agent:
    api_url: (( concat "http://" jobs.covalence.networks[0].static_ips[0] ":9201" ))